// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var StyleSheet$BsReactNative = require("bs-react-native/lib/js/src/styleSheet.js");

var styles = StyleSheet$BsReactNative.create({
      app: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(1),
            /* :: */[
              Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#F5FCFF"])),
              /* :: */[
                Style$BsReactNative.marginHorizontal(/* Auto */0),
                /* :: */[
                  Style$BsReactNative.maxWidth(/* Pt */Block.__(0, [500])),
                  /* [] */0
                ]
              ]
            ]
          ]),
      logo: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.height(/* Pt */Block.__(0, [80])),
            /* [] */0
          ]),
      header: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.padding(/* Pt */Block.__(0, [20])),
            /* [] */0
          ]),
      title: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontWeight(/* Bold */737455525),
            /* :: */[
              Style$BsReactNative.fontSize(/* Float */Block.__(0, [24])),
              /* :: */[
                Style$BsReactNative.marginVertical(/* Pt */Block.__(0, [16])),
                /* :: */[
                  Style$BsReactNative.textAlign(/* Center */3),
                  /* [] */0
                ]
              ]
            ]
          ]),
      text: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.lineHeight(24),
            /* :: */[
              Style$BsReactNative.fontSize(/* Float */Block.__(0, [18])),
              /* :: */[
                Style$BsReactNative.marginVertical(/* Pt */Block.__(0, [16])),
                /* :: */[
                  Style$BsReactNative.textAlign(/* Center */3),
                  /* [] */0
                ]
              ]
            ]
          ]),
      link: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.color(/* String */Block.__(0, ["#1B95E0"])),
            /* [] */0
          ]),
      buttonContainer: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.margin(/* Pt */Block.__(0, [20])),
            /* [] */0
          ])
    });

var button = "#1B95E0";

exports.button = button;
exports.styles = styles;
/* styles Not a pure module */
