// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative = require("react-native");
var Styles$RnwebCxTest = require("./styles/Styles.bs.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");

var component = ReasonReact.statelessComponent("Link");

function make(href, style, value, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var linkStyle = style !== undefined ? Style$BsReactNative.concat(/* :: */[
                      Styles$RnwebCxTest.styles.link,
                      /* :: */[
                        Caml_option.valFromOption(style),
                        /* [] */0
                      ]
                    ]) : Styles$RnwebCxTest.styles.link;
              return ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, (function (param) {
                                ReactNative.Linking.openURL(href).then((function (param) {
                                        return Promise.resolve((console.log("opened " + href), /* () */0));
                                      }));
                                return /* () */0;
                              }), undefined, undefined, Caml_option.some(linkStyle), undefined, undefined, undefined, undefined, undefined, undefined, value, /* array */[]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
